# optimization_config.py
"""
Quantum Workload Optimization Config
Defines the 44-strategy registry with categories, default flags, priorities,
and mock preflight impact parameters for sequential screening.
"""

STRATEGIES = [
    # Tier 1: Direct Latency (Circuit Routing/Layout)
    {
        "id": "OP-01",
        "name": "GATE_FUSION",
        "category": "optimization",
        "enabled": False,
        "priority": 1,
        "description": "Fuses adjacent quantum gates to reduce circuit depth and overhead",
        "applicable_workloads": ["period_finding", "discrete_log", "lattice"],
        "latency_multiplier": 0.95,
        "cost_multiplier": 1.0,
        "error_multiplier": 1.0,
    },
    {
        "id": "OP-09",
        "name": "QUBIT_LAYOUT",
        "category": "optimization",
        "enabled": False,
        "priority": 2,
        "description": "Optimizes physical qubit mapping to minimize swap gate count",
        "applicable_workloads": ["period_finding", "discrete_log"],
        "latency_multiplier": 0.90,
        "cost_multiplier": 0.95,
        "error_multiplier": 0.98,
    },
    {
        "id": "OP-10",
        "name": "GREEDY_SWAP",
        "category": "optimization",
        "enabled": False,
        "priority": 3,
        "description": "Applies greedy swap insertion during circuit routing",
        "applicable_workloads": ["period_finding", "discrete_log"],
        "latency_multiplier": 0.92,
        "cost_multiplier": 1.0,
        "error_multiplier": 1.0,
    },
    {
        "id": "OP-14",
        "name": "DAG_OPT",
        "category": "optimization",
        "enabled": False,
        "priority": 4,
        "description": "Optimizes circuit DAG by scheduling independent gates in parallel",
        "applicable_workloads": ["period_finding", "discrete_log", "lattice"],
        "latency_multiplier": 0.94,
        "cost_multiplier": 1.0,
        "error_multiplier": 1.0,
    },
    {
        "id": "OP-15",
        "name": "BACKEND_AWARE_ROUTING",
        "category": "routing",
        "enabled": False,
        "priority": 5,
        "description": "Routes operations to the physical backend with lowest queue latency",
        "applicable_workloads": ["period_finding", "discrete_log", "lattice"],
        "latency_multiplier": 1.0,  # Handled logically in option selection
        "cost_multiplier": 1.0,
        "error_multiplier": 1.0,
    },

    # Tier 2: Execution Mode (Hardware selection & caching)
    {
        "id": "OP-19",
        "name": "ASYNC_BATCHING",
        "category": "execution",
        "enabled": False,
        "priority": 6,
        "description": "Batches independent jobs for concurrent execution and lower queue overhead",
        "applicable_workloads": ["period_finding", "discrete_log", "lattice"],
        "latency_multiplier": 1.0,
        "cost_multiplier": 0.90,
        "error_multiplier": 1.0,
    },
    {
        "id": "OP-20",
        "name": "PRECOMPILE_CACHE",
        "category": "execution",
        "enabled": False,
        "priority": 7,
        "description": "Caches compiled circuit binaries to eliminate compilation overhead",
        "applicable_workloads": ["period_finding", "discrete_log", "lattice"],
        "latency_multiplier": 0.98,
        "cost_multiplier": 1.0,
        "error_multiplier": 1.0,
    },
    {
        "id": "OP-21",
        "name": "HYBRID_EXEC",
        "category": "execution",
        "enabled": False,
        "priority": 8,
        "description": "Dynamically partitions classical-quantum parts of the workload",
        "applicable_workloads": ["period_finding", "discrete_log", "lattice"],
        "latency_multiplier": 0.95,
        "cost_multiplier": 0.95,
        "error_multiplier": 1.0,
    },
    {
        "id": "OP-22",
        "name": "LOCAL_SIM_FALLBACK",
        "category": "execution",
        "enabled": False,
        "priority": 9,
        "description": "Enforces fallback to local classical simulation for small problem sizes",
        "applicable_workloads": ["period_finding", "discrete_log", "lattice"],
        "latency_multiplier": 1.0,  # Handled logically in option selection
        "cost_multiplier": 1.0,
        "error_multiplier": 1.0,
    },
    {
        "id": "OP-23",
        "name": "GPU_ACCEL",
        "category": "execution",
        "enabled": False,
        "priority": 10,
        "description": "Forces GPU acceleration for matrix operations and classical solver blocks",
        "applicable_workloads": ["period_finding", "discrete_log", "lattice"],
        "latency_multiplier": 1.0,  # Handled logically in option selection
        "cost_multiplier": 1.0,
        "error_multiplier": 1.0,
    },
    {
        "id": "OP-24",
        "name": "ADAPTIVE_SHOTS",
        "category": "execution",
        "enabled": False,
        "priority": 11,
        "description": "Dynamically adjusts shot counts based on statistical variance",
        "applicable_workloads": ["period_finding", "discrete_log"],
        "latency_multiplier": 0.92,
        "cost_multiplier": 0.85,
        "error_multiplier": 1.05,
    },
    {
        "id": "OP-16",
        "name": "COHERENCE_PRIO",
        "category": "routing",
        "enabled": False,
        "priority": 12,
        "description": "Routes circuits to qubits with maximum coherence time",
        "applicable_workloads": ["period_finding", "discrete_log"],
        "latency_multiplier": 1.0,
        "cost_multiplier": 1.05,
        "error_multiplier": 0.50,
    },

    # Tier 3: Circuit Optimization (Gate reductions)
    {
        "id": "OP-02",
        "name": "COMMUTATION_RULES",
        "category": "optimization",
        "enabled": False,
        "priority": 13,
        "description": "Commutes gates to enable cancellation and gate reduction",
        "applicable_workloads": ["period_finding", "discrete_log"],
        "latency_multiplier": 0.97,
        "cost_multiplier": 1.0,
        "error_multiplier": 1.0,
    },
    {
        "id": "OP-03",
        "name": "NATIVE_GATE_MAPPING",
        "category": "optimization",
        "enabled": False,
        "priority": 14,
        "description": "Translates high-level gates directly to hardware native primitives",
        "applicable_workloads": ["period_finding", "discrete_log"],
        "latency_multiplier": 0.96,
        "cost_multiplier": 1.0,
        "error_multiplier": 0.98,
    },
    {
        "id": "OP-04",
        "name": "T_GATE_MIN",
        "category": "optimization",
        "enabled": False,
        "priority": 15,
        "description": "Minimizes expensive T-gate counts in quantum arithmetic",
        "applicable_workloads": ["period_finding", "discrete_log"],
        "latency_multiplier": 0.95,
        "cost_multiplier": 1.0,
        "error_multiplier": 1.0,
    },
    {
        "id": "OP-05",
        "name": "UNITARY_BLOCK_DECOMP",
        "category": "optimization",
        "enabled": False,
        "priority": 16,
        "description": "Optimally decomposes multi-qubit unitaries into 2-qubit blocks",
        "applicable_workloads": ["period_finding", "discrete_log"],
        "latency_multiplier": 0.94,
        "cost_multiplier": 1.0,
        "error_multiplier": 0.95,
    },
    {
        "id": "OP-07",
        "name": "MCX_DECOMP",
        "category": "optimization",
        "enabled": False,
        "priority": 17,
        "description": "Applies efficient multi-controlled X decomposition with ancillas",
        "applicable_workloads": ["period_finding", "discrete_log"],
        "latency_multiplier": 0.98,
        "cost_multiplier": 1.0,
        "error_multiplier": 1.0,
    },
    {
        "id": "OP-12",
        "name": "PEEPHOLE_OPT",
        "category": "optimization",
        "enabled": False,
        "priority": 18,
        "description": "Applies localized pattern matching and gate reductions",
        "applicable_workloads": ["period_finding", "discrete_log", "lattice"],
        "latency_multiplier": 0.96,
        "cost_multiplier": 1.0,
        "error_multiplier": 1.0,
    },
    {
        "id": "OP-43",
        "name": "DEAD_CODE_ELIM",
        "category": "optimization",
        "enabled": False,
        "priority": 19,
        "description": "Removes unused gates, ancillas, and operations",
        "applicable_workloads": ["period_finding", "discrete_log", "lattice"],
        "latency_multiplier": 0.99,
        "cost_multiplier": 1.0,
        "error_multiplier": 1.0,
    },
    {
        "id": "OP-11",
        "name": "CUSTOM_TRANSPILES",
        "category": "optimization",
        "enabled": False,
        "priority": 20,
        "description": "Applies domain-specific handcrafted transpilation passes",
        "applicable_workloads": ["period_finding", "discrete_log", "lattice"],
        "latency_multiplier": 0.95,
        "cost_multiplier": 1.0,
        "error_multiplier": 0.98,
    },

    # Tier 4: Algorithmic (Advanced mathematical cuts)
    {
        "id": "OP-06",
        "name": "SYMMETRY_EXPLOIT",
        "category": "encoding",
        "enabled": False,
        "priority": 21,
        "description": "Uses problem symmetry to reduce state space and dimensionality",
        "applicable_workloads": ["period_finding", "discrete_log", "lattice"],
        "latency_multiplier": 0.90,
        "cost_multiplier": 0.95,
        "error_multiplier": 1.0,
    },
    {
        "id": "OP-08",
        "name": "APPROX_UNITARY",
        "category": "optimization",
        "enabled": False,
        "priority": 22,
        "description": "Approximates high-depth unitaries with low-rank factorizations",
        "applicable_workloads": ["period_finding", "discrete_log", "lattice"],
        "latency_multiplier": 0.85,
        "cost_multiplier": 0.90,
        "error_multiplier": 1.50,  # Trades fidelity for significant latency gain!
    },
    {
        "id": "OP-13",
        "name": "DYNAMIC_CIRCUIT",
        "category": "execution",
        "enabled": False,
        "priority": 23,
        "description": "Enables mid-circuit measurement and classical feedforward",
        "applicable_workloads": ["period_finding", "discrete_log"],
        "latency_multiplier": 0.93,
        "cost_multiplier": 1.0,
        "error_multiplier": 1.02,
    },
    {
        "id": "OP-17",
        "name": "CIRCUIT_CUTTING",
        "category": "execution",
        "enabled": False,
        "priority": 24,
        "description": "Cuts large circuits into subcircuits to fit smaller QPUs",
        "applicable_workloads": ["period_finding", "discrete_log"],
        "latency_multiplier": 0.90,
        "cost_multiplier": 1.10,
        "error_multiplier": 1.10,
    },
    {
        "id": "OP-28",
        "name": "AMPLITUDE_ENCODING",
        "category": "encoding",
        "enabled": False,
        "priority": 25,
        "description": "Uses state-amplitude encoding to reduce qubit requirements logarithmically",
        "applicable_workloads": ["period_finding", "discrete_log"],
        "latency_multiplier": 0.88,
        "cost_multiplier": 1.0,
        "error_multiplier": 1.05,
    },
    {
        "id": "OP-29",
        "name": "BASIS_COMPRESSION",
        "category": "encoding",
        "enabled": False,
        "priority": 26,
        "description": "Compresses computation basis representation of operators",
        "applicable_workloads": ["period_finding", "discrete_log", "lattice"],
        "latency_multiplier": 0.92,
        "cost_multiplier": 0.95,
        "error_multiplier": 1.0,
    },
    {
        "id": "OP-30",
        "name": "BINARY_UNARY_ARITH",
        "category": "encoding",
        "enabled": False,
        "priority": 27,
        "description": "Applies binary-to-unary arithmetic encoding conversions",
        "applicable_workloads": ["period_finding", "discrete_log"],
        "latency_multiplier": 0.96,
        "cost_multiplier": 1.0,
        "error_multiplier": 1.0,
    },
    {
        "id": "OP-31",
        "name": "RECURSIVE_QPE",
        "category": "encoding",
        "enabled": False,
        "priority": 28,
        "description": "Uses recursive quantum phase estimation for precision scaling",
        "applicable_workloads": ["period_finding", "discrete_log"],
        "latency_multiplier": 0.90,
        "cost_multiplier": 0.90,
        "error_multiplier": 1.0,
    },

    # Tier 5: Error / Quality
    {
        "id": "OP-25",
        "name": "ERROR_MITIGATION",
        "category": "error_mitigation",
        "enabled": False,
        "priority": 29,
        "description": "Applies zero-noise extrapolation to reduce expectation value error",
        "applicable_workloads": ["period_finding", "discrete_log"],
        "latency_multiplier": 1.05,
        "cost_multiplier": 1.20,
        "error_multiplier": 0.50,
    },
    {
        "id": "OP-26",
        "name": "READOUT_CALIB",
        "category": "error_mitigation",
        "enabled": False,
        "priority": 30,
        "description": "Mitigates measurement readout errors using calibration matrices",
        "applicable_workloads": ["period_finding", "discrete_log"],
        "latency_multiplier": 1.05,
        "cost_multiplier": 1.05,
        "error_multiplier": 0.80,
    },
    {
        "id": "OP-27",
        "name": "PROBABILISTIC_ERR_CANCEL",
        "category": "error_mitigation",
        "enabled": False,
        "priority": 31,
        "description": "Applies probabilistic error cancellation to mitigate hardware noise",
        "applicable_workloads": ["period_finding", "discrete_log"],
        "latency_multiplier": 1.10,
        "cost_multiplier": 1.50,
        "error_multiplier": 0.30,
    },
    {
        "id": "OP-32",
        "name": "PARAM_INIT",
        "category": "optimization",
        "enabled": False,
        "priority": 32,
        "description": "Utilizes machine-learning priors for parameter initialization",
        "applicable_workloads": ["period_finding", "discrete_log", "lattice"],
        "latency_multiplier": 0.95,
        "cost_multiplier": 0.95,
        "error_multiplier": 1.0,
    },
    {
        "id": "OP-41",
        "name": "CORRECTIVE_FEEDBACK",
        "category": "error_mitigation",
        "enabled": False,
        "priority": 33,
        "description": "Applies iterative corrective feedback loop based on mid-run calibration",
        "applicable_workloads": ["period_finding", "discrete_log", "lattice"],
        "latency_multiplier": 1.10,
        "cost_multiplier": 1.10,
        "error_multiplier": 0.70,
    },
    {
        "id": "OP-44",
        "name": "PULSE_CONTROL",
        "category": "error_mitigation",
        "enabled": False,
        "priority": 34,
        "description": "Directly manipulates hardware pulses to bypass standard gate compilations",
        "applicable_workloads": ["period_finding", "discrete_log"],
        "latency_multiplier": 1.15,
        "cost_multiplier": 1.10,
        "error_multiplier": 0.60,
    },
    {
        "id": "OP-18",
        "name": "VAR_PARAM_SHIFT",
        "category": "optimization",
        "enabled": False,
        "priority": 35,
        "description": "Optimizes parameter shifts dynamically during variational loops",
        "applicable_workloads": ["period_finding", "discrete_log"],
        "latency_multiplier": 0.96,
        "cost_multiplier": 1.0,
        "error_multiplier": 1.0,
    },
    {
        "id": "OP-35",
        "name": "DEPTH_ACCURACY_PROFILING",
        "category": "testing",
        "enabled": False,
        "priority": 36,
        "description": "Profiles circuit depth to find the optimal speed/accuracy trade-off",
        "applicable_workloads": ["period_finding", "discrete_log", "lattice"],
        "latency_multiplier": 1.0,
        "cost_multiplier": 1.0,
        "error_multiplier": 1.0,
    },

    # Tier 6: Infrastructure / Testing (No latency/cost impact)
    {
        "id": "OP-33",
        "name": "UNIT_TESTING",
        "category": "testing",
        "enabled": False,
        "priority": 37,
        "description": "Enables circuit unit test assertions before deployment",
        "applicable_workloads": ["period_finding", "discrete_log", "lattice"],
        "latency_multiplier": 1.0,
        "cost_multiplier": 1.0,
        "error_multiplier": 1.0,
    },
    {
        "id": "OP-34",
        "name": "CIRCUIT_VERSIONING",
        "category": "tooling",
        "enabled": False,
        "priority": 38,
        "description": "Versions circuit models in a local git repository for provenance",
        "applicable_workloads": ["period_finding", "discrete_log", "lattice"],
        "latency_multiplier": 1.0,
        "cost_multiplier": 1.0,
        "error_multiplier": 1.0,
    },
    {
        "id": "OP-36",
        "name": "MOCK_BACKENDS",
        "category": "testing",
        "enabled": False,
        "priority": 39,
        "description": "Enables unit tests on local classical mock environments",
        "applicable_workloads": ["period_finding", "discrete_log", "lattice"],
        "latency_multiplier": 1.0,
        "cost_multiplier": 1.0,
        "error_multiplier": 1.0,
    },
    {
        "id": "OP-37",
        "name": "BOTTLENECK_ANALYSIS",
        "category": "testing",
        "enabled": False,
        "priority": 40,
        "description": "Analyzes classical/quantum graph execution bottlenecks",
        "applicable_workloads": ["period_finding", "discrete_log", "lattice"],
        "latency_multiplier": 1.0,
        "cost_multiplier": 1.0,
        "error_multiplier": 1.0,
    },
    {
        "id": "OP-38",
        "name": "AUTO_DOC",
        "category": "tooling",
        "enabled": False,
        "priority": 41,
        "description": "Automatically generates circuit layouts and PDF diagrams",
        "applicable_workloads": ["period_finding", "discrete_log", "lattice"],
        "latency_multiplier": 1.0,
        "cost_multiplier": 1.0,
        "error_multiplier": 1.0,
    },
    {
        "id": "OP-39",
        "name": "BACKEND_ABSTRACTION",
        "category": "tooling",
        "enabled": False,
        "priority": 42,
        "description": "Abstracts target hardware details behind high-level interfaces",
        "applicable_workloads": ["period_finding", "discrete_log", "lattice"],
        "latency_multiplier": 1.0,
        "cost_multiplier": 1.0,
        "error_multiplier": 1.0,
    },
    {
        "id": "OP-40",
        "name": "VISUALIZATION",
        "category": "tooling",
        "enabled": False,
        "priority": 43,
        "description": "Generates interactive 3D matplotlib plots of quantum states",
        "applicable_workloads": ["period_finding", "discrete_log", "lattice"],
        "latency_multiplier": 1.0,
        "cost_multiplier": 1.0,
        "error_multiplier": 1.0,
    },
    {
        "id": "OP-42",
        "name": "CROSS_PLATFORM",
        "category": "tooling",
        "enabled": False,
        "priority": 44,
        "description": "Adapts execution instructions to multiple dialect definitions",
        "applicable_workloads": ["period_finding", "discrete_log", "lattice"],
        "latency_multiplier": 1.0,
        "cost_multiplier": 1.0,
        "error_multiplier": 1.0,
    },
]

def get_enabled_strategies():
    """Returns a list of currently enabled strategies."""
    return [s for s in STRATEGIES if s["enabled"]]

def reset_strategies():
    """Disables all strategies in the registry."""
    for s in STRATEGIES:
        s["enabled"] = False

def enable_strategy(strategy_id):
    """Enables a strategy by its ID."""
    for s in STRATEGIES:
        if s["id"] == strategy_id:
            s["enabled"] = True
            return True
    return False

def get_multipliers():
    """Calculates combined latency, cost, and error multipliers from enabled strategies."""
    latency_mult = 1.0
    cost_mult = 1.0
    error_mult = 1.0
    
    for s in STRATEGIES:
        if s["enabled"]:
            latency_mult *= s.get("latency_multiplier", 1.0)
            cost_mult *= s.get("cost_multiplier", 1.0)
            error_mult *= s.get("error_multiplier", 1.0)
            
    return latency_mult, cost_mult, error_mult
